USE test;
CREATE TABLE IF NOT EXISTS test.user (
`ID` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
`FIRST_NAME` VARCHAR(25) NOT NULL,
`LAST_NAME` VARCHAR(25) NOT NULL,
`AGE` INT NOT NULL,
`ADMIN` BIT(1) NOT NULL DEFAULT 0,
`CREATED_DATE` TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(0));
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Jack', 'Fisher', '21');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Lew', 'Oledin', '23');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Egor', 'Prjanik', '56');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Lena', 'Prjanik', '1');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Ольга', 'Егорова', '15');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Иван', 'Капустин', '24');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Лев', 'Лещенко', '28');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Eugen', 'Bowl', '33');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Mick', 'Jalt', '37');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Antony', 'Girl', '34');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE) VALUES ('Sonya', 'Oreh', '39');
INSERT INTO test.user (FIRST_NAME, LAST_NAME, AGE, ADMIN) VALUES ('Alsu', 'Barash', '29', 1);
